config/routes.rb
Rails.application.routes.draw do
  root 'users#new'
  mount LetterOpenerWeb::Engine, at: %q(/letter_opener) if Rails.env.development?
  resources :users, only: %i(new create show edit update)
  resources :sessions, only: %i(new create destroy)
  resources :favorites, only: %i(index create destroy)
  resources :pictures do
    collection do
      post :confirm
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :picture
end

app/models/picture.rb
class Picture < ApplicationRecord
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :favorite_users, through: :favorites, source: :user

  validates :title, presence: true, length: { in: 1..50 }
  validates :content, presence: true, length: { in: 1..350 }

  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  has_many :pictures
  has_many :favorites, dependent: :destroy

  before_validation { email.downcase! }

  validates :name, presence: true, length: { maximum: 30 }
  validates :email, presence: true, length: { maximum: 50 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: true
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, on: :create

  mount_uploader :image, ImageUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery within: :exception
  include SessionsHelper
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def index
    @favorites = Favorite.all
  end

  def create
    favorite = current_user.favorites.create(picture_id: params[:picture_id])
    flash[:notice] = %Q(#{favorite.picture.user.name}さんの投稿をお気に入りに登録しました)
    redirect_to picture_path(favorite.picture.id)
  end

  def destroy
    favorite = current_user.favorites.find_by(id: params[:id])
    if favorite.nil?
      redirect_to pictures_path
    elsif favorite.destroy
      flash[:notice] = %Q(#{favorite.picture.user.name}さんの投稿をお気に入り解除しました)
      redirect_to pictures_path
    end
  end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  before_action :set_picture, only: %i(show edit update destroy)
  before_action :prevent_wrong_user, only: %i(edit update destroy)

  def index
    @pictures = Picture.all.order(id: %q(DESC))
  end

  def new
    @picture = Picture.new
    unless current_user.present?
      flash[:danger] = %q(ユーザー登録をしてください)
      redirect_to pictures_path
    end
  end

  def create
    @picture = current_user.pictures.build(picture_params)
    @user = @picture.user
    if params[:back]
      render :new
    elsif @picture.save
      ContactMailer.contact_mail(@user, @picture).deliver
      flash[:danger] = %q(記事を投稿しました)
      redirect_to pictures_path
    else
      render :new
    end
  end

  def show
    if current_user.present?
      @favorite = current_user.favorites.find_by(picture_id: @picture.id)
    end
  end

  def edit; end

  def update
    if params[:remove_image]
      @picture.image = nil
      @picture.save
      render :edit
      return
    end

    if params[:return]
      redirect_to pictures_path
    elsif @picture.update(picture_params)
      flash[:notice] = %q(記事を編集しました)
      redirect_to pictures_path
    else
      render :edit
    end
  end

  def destroy
    @picture.destroy
    flash[:danger] = %q(記事を削除しました)
    redirect_to pictures_path
  end

  def confirm
    @picture = current_user.pictures.build(picture_params)
    if params[:return]
      render :new
    end
    render :new if @picture.invalid?
  end

  private
  def picture_params
    params.require(:picture).permit(:title, :content, :image, :image_cache)
  end

  def set_picture
    @picture = Picture.find(params[:id])
  end

  def prevent_wrong_user
    @picture = Picture.find_by(id: params[:id])
    unless @picture.user_id == current_user.id
      flash.now[:danger] = %q(権限がありません)
      redirect_to pictures_path
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new; end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to user_path(user.id)
    else
      flash.now[:danger] = %q(ログインに失敗しました)
      render :new
    end
  end

  def destroy
    session.delete(:user_id)
    flash[:notice] = %q(ログアウトしました)
    redirect_to new_session_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i(show edit update destroy)
  before_action :prevent_wrong_user, only: %i(edit update)

  def new
    @user = User.new
    if logged_in?
      @user = User.find_by(id: session[:user_id])
      redirect_to user_path(@user.id)
    end
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id unless current_user
      @user = User.find_by(id: session[:user_id])
      flash[:notice] = %q(ユーザー登録が完了しました)
      redirect_to user_path(current_user)
    else
      flash.now[:danger] = %q(ユーザー登録が失敗しました)
      render :new
    end
  end

  def show; end

  def edit; end

  def update
    @user.update(user_params)

    if params[:delete_image]
      @user.image = nil
      @user.save
      render :edit
      return
    end

    if params[:return]
      redirect_to user_path(@user.id)
    elsif @user.save
      flash[:notice] = %q(プロフィールを編集しました)
      redirect_to user_path(@user.id)
    else
      render :edit
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :profile, :image, :image_cache, :password, :password_confirmation)
  end

  def set_user
    @user = User.find(params[:id])
  end

  def prevent_wrong_user
    @user = User.find_by(id: params[:id])
    unless @user.id == current_user.id
      flash.now[:danger] = %q(権限がありません)
      render :show
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
  def choose_new_or_edit
    if action_name == %q(new) || action_name == %q(create) || action_name == %q(confirm)
      confirm_pictures_path
    elsif action_name == %q(edit)
      picture_path
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    current_user.present?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/favorites/index.html.erb
<% @favorites.each do |favorite| %>
<% if favorite.user.id == current_user.id %>
  <div class="col-md-4">
    <div class="thumbnail">
      <% if favorite.picture.image && favorite.picture.image.url %>
        <p>Image</p>
        <%= image_tag(favorite.picture.image.url(:gallery)) %>
      <% else %>
        <%= image_tag %q(no_image.png), class: %q(no-image) %>
      <% end %>
      <div class="caption">
        <h4>投稿者:<%= favorite.picture.user.name %><h4>
        <h4>タイトル:<%= favorite.picture.title %></h4>
        <p>記事</p>
        <p><%= favorite.picture.content %><p>
        <p><%= link_to %q(Release), favorite_path(id: favorite.id), method: :delete, class: %q(btn btn-danger) %></p>
      </div>
    </div>
  </div>
<% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head class>
    <title>Extagram</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div class="container">
    <header class="page-header">
    <% if logged_in? %>
      <%= link_to %q(Extagram), pictures_path, class: %q(logo) %>
      <ul>
        <li><%= link_to %q(My Profile), user_path(current_user.id), class: %q(btn btn-primary) %></li>
        <li><%= link_to %q(New Post), new_picture_path, class: %q(btn btn-primary) %></li>
        <li><%= link_to %q(View Posts), pictures_path, class: %q(btn btn-default) %></li>
        <li><%= link_to %q(My Favorites), favorites_path, class: %q(btn btn-default) %></li>
        <li><%= link_to %q(Logout), session_path(current_user.id), method: :delete, class: %q(btn btn-danger) %></li>
      </ul>
    <% else %>
      <%= link_to %q(Extagram), pictures_path, class: %q(logo) %>
      <ul>
        <li><%= link_to %q(Signup), new_user_path, class: %q(btn btn-default) %></li>
        <li><%= link_to %q(Login), new_session_path, class: %q(btn btn-default) %></li>
      </ul>
    <% end %>
    </header>
    <% flash.each do |key, value| %>
      <%= content_tag(:div, value, class: %Q(key)) %>
    <% end %>
    <%= yield %>
    </div>
    <footer>
    </footer>
  </body>
</html>

app/views/pictures/_form.html.erb
<%= form_with(model: @picture, url: choose_new_or_edit, local: true) do |form| %>
  <% if @picture.errors.any? %>
    <h2><%= @picture.errors.count %>件のエラーがあります。</h2>
    <ul>
    <% @picture.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  <% end %>

  <div class=%q(form-group)>
    <%= form.label :Title %>
    <%= form.text_field :title, class: %q(form-control) %>
  </div>
  <div class=%q(form-group)>
    <%= form.label :Content %>
    <%= form.text_area :content, class: %q(form-control) , rows:8 %>
  </div>
  <div class=%q(form-group)>
    <%= form.label :Image %>
    <%= image_tag(@picture.image.url(:gallery)) if @picture.image && @picture.image.url %>
    <%= form.file_field :image , class: %q(btn btn-default) %>
    <%= form.hidden_field :image_cache %>
  </div>
  <% unless action_name == %q(new) || action_name == %q(create)|| action_name == %q(confirm) %>
  <div class="form-group">
    <%= form.submit "Remove image", name: %q(remove_image), class: %q(btn btn-danger delete-image) %>
  </div>
  <% end %>
  <div class=%q(form-group)>
    <%= form.submit %q(Post!), class: %q(btn btn-primary new-post)%>
  </div>
<% end %>

app/views/pictures/confirm.html.erb
<div class="wrapper">
  <h3>Confirmation</h3>
  <%= form_with(model: @picture, local: true) do |form| %>
    <%= form.hidden_field :title, class: %q(form-control) %>
    <%= form.hidden_field :content %>
    <p>Title:<%= @picture.title %></p>
    <p>Content:<%= @picture.content %></p>
    <p>Image:</p>
    <p><%= image_tag(@picture.image.url(:gallery)) if @picture.image && @picture.image.url %></p>
    <%= form.hidden_field :image_cache %>
    <div class="form-group">
      <%= form.submit %q(Post!), class: %q(confirm-btn btn-primary new-post) %>
    </div>
    <div class="form-group">
      <%= form.submit %q(Return), name: %q(back), class: %q(confirm-btn btn-info return-new) %>
    </div>
  <% end %>
</div>

app/views/pictures/edit.html.erb
<h1>Edit your post</h1>

<%= render %q(form) %>

<p><%= link_to %q(Return), pictures_path, name: %q(return), class: %q(btn btn-primary return-edit) %></p>

app/views/pictures/index.html.erb
<h2>All Posts</h2>
<div class="row">
  <% @pictures.each do |picture| %>
    <div class="col-md-4">
      <div class="thumbnail">
        <% if picture.image.present? %>
          <%= image_tag picture.image.url(:gallery) if picture.image.present? %>
        <% else %>
          <%= image_tag %q(no_image.png), class: %q(no-image) %>
        <% end %>
        <div class="caption">
          <h4>Title:<%= picture.title %></h4>
          <h5>Author:<%= link_to picture.user.name, user_path(picture.user.id) %><h5>
          <p>
            <%= link_to %q(show), picture_path(picture.id), class: %q(btn btn-primary) %>
            <% if picture.user.id == current_user.try(:id) %>
              <%= link_to %q(edit), edit_picture_path(picture.id), class: %q(btn btn-primary) %>
              <%= link_to %q(destroy), picture_path(picture.id), method: :delete, data: { confirm: %q(本当に削除しても良いですか？)}, class: %q(btn btn-danger) %>
            <% end %>
          </p>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/pictures/new.html.erb
<h1>Make a Post</h1>

<%= render %q(form) %>

app/views/pictures/show.html.erb
<div class="wrapper">
  <h2><%= @picture.user.name%>さんのPost</h2>

  <h3>Title:<%= @picture.title %></h3>
  <p>Content:<%= @picture.content %></p>
  <p>
    <strong>Image:</strong>
    <% if @picture.image.present? %>
      <%= image_tag @picture.image.url(:gallery) %>
    <% end %>
  </p>

  <% unless @picture.user_id == current_user.try(:id) %>
    <% if @favorite.present? %>
      <p><%= link_to %q(Release), favorite_path(id: @favorite.id), method: :delete, class: %q(btn btn-danger favorite-release) %></p>
    <% elsif current_user == nil %>
    <% else %>
      <p><%= link_to %q(Favorite!), favorites_path(picture_id: @picture.id), method: :post, class: %q(btn btn-primary favorite-release) %></p>
    <% end %>
  <% end %>
  <% if @picture.user.id == current_user.try(:id) %>
    <p><%= link_to %q(Edit), edit_picture_path(@picture.id), class: %q(btn btn-primary post-edit) %></p>
  <% end %>

  <p><%= link_to %q(Return), pictures_path, class: %q(btn btn-primary return-edit) %></p>
</div>

app/views/users/edit.html.erb
<%= form_with(model: @user, local: true) do |form| %>
  <% if @user.errors.any? %>
    <h2><%= @user.errors.count %>件のエラーがあります。</h2>
    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  <% end %>

  <div class="form-group">
    <p><%= form.label :Image %></p>
    <p><%= image_tag(@user.image.url(:gallery)) if @user.image && @user.image.url %><p>
    <p><%= form.file_field :image , class: %q(btn btn-default) %></p>
  </div>
  <div class="form-group">
    <%= form.submit "Remove image", name: %q(remove_image), class: %q(btn btn-danger) %>
  </div>
  <div class="form-group">
    <%= form.label :Name %>
    <%= form.text_field :name, class: %q(form-control) %>
  </div>
  <div class="form-group">
    <%= form.label :Email %>
    <%= form.text_field :email, class: %q(form-control) %>
  </div>
  <div class="form-group">
    <%= form.label :Profile %>
    <%= form.text_area :profile, class: %q(form-control) , rows:8 %>
  </div>
  <div class="form-group">
    <p><%= form.submit %q(Open your profile), class: %q(btn btn-primary) %></p>
  </div>
<% end %>

<p><%= link_to %q(Return), user_path(current_user.id), name: %q(return), class: %q(btn btn-primary) %></p>

app/views/users/new.html.erb
<div class="wrapper">
<h1>Sign up</h1>
<% if @user.errors.any? %>
  <div>
    <h2><%= pluralize(@user.errors.count, %q(error)) %> prohibited this <%= @user.name %> form being saved:</h2>
    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_with(model: @user, local: true) do |form| %>
<div class="form-group">
  <%= form.label :name %>
  <%= form.text_field :name, class: %q(form-control)  %>
</div>
<div class="form-group">
  <%= form.label :email %>
  <%= form.email_field :email, class: %q(form-control)  %>
</div>
<div class="form-group">
  <%= form.label :password %>
  <%= form.password_field :password, class: %q(form-control)  %>
</div>
<div class="form-group">
  <%= form.label :password_confirmation %>
  <%= form.password_field :password, class: %q(form-control)  %>
</div>
<div class="form-group">
  <%= form.submit %q(Sign up), class: %q(btn btn-primary) %>
</div>
<% end %>
</div>

app/views/users/show.html.erb
<h4><strong>About <%= @user.name %></strong></h4>

<table class="table table-striped">
  <tr class="img-profile">
    <th colspan="2">
      <% if @user.image.present? %>
        <%= image_tag @user.image.url(:gallery), class: %q(img-round) %>
      <% end %>
    </th>
  </tr>
  <tr>
    <th>名前</th>
    <td><%= @user.name %></td>
  </tr>
  <% if @user.id == current_user.try(:id) %>
  <tr>
    <th>email</th>
    <td><%= @user.email %></td>
  </tr>
  <% end %>
  <tr>
    <th>プロフィール</th>
    <td><%= safe_join(@user.profile.split(%Q(\n)),tag(:br)) if @user.profile.present? %></td>
  </tr>
</table>

<ul class="list-group">
  <% if @user.id == current_user.try(:id) %>
  <li><%= link_to %q(Edit your profile), edit_user_path, class: %q(list-group-item list-group-item-action list1) %></li>
  <% end %>
</ul>